// tests-frameworks/svelte/src/components/simpleNumberList.svelte
<script lang="ts">
	import '../app.css';
   
   import useDragAndDrop from '../../../../src/svelte/useDragAndDrop.ts';
	let numbers = $state([1, 2, 3]);
   const [dragAnDrop, insertAt, removeAt] = useDragAndDrop(numbers,{
      removingClass: "removed",
      delayBeforeRemove: 400,
   });
   const RemoveFirst = () => {
      if (numbers.length > 0) {
         removeAt(0);
      }
   }
   const Append=()=>{
      const maxNumber = (numbers.length>0?Math.max(...numbers):0)
      insertAt(numbers.length,maxNumber+1)
   }
</script>

<ul class="bg-slate-700 flex flex-col gap-2 max-w-2xl p-2 mb-2" use:dragAnDrop>
   {#each numbers as number, index (number)}
      <li class="bg-slate-400 number" data-index={index}>
         {number}
      </li>
   {/each}
</ul>
<div class="flex justify-between max-w-2xl">
   <button class="bg-slate-400 p-2 rounded-md hover:bg-slate-600 w-xs" onclick={RemoveFirst}>Remove first</button>
   <button class="bg-slate-400 p-2 rounded-md hover:bg-slate-600 w-xs" onclick={Append}>Append</button>

</div>
<style>
   .number {
      opacity: 1;
      transition: opacity 200ms ease;
   }
   :global(.number.removed) {
      opacity: 0;
   }
   :global(.number.from-inserting){
      opacity: 0;
   }
</style>

// tests-frameworks/react/src/components/simpleNumberList.tsx
import React from 'react';
import  './simpleNumberList.css';
import useDragAndDrop from '../../../../src/react/useDragAndDrop';
const NumberList: React.FC = () => {
  const [parent, numbers, _, insertAt, removeAt] = useDragAndDrop<number, HTMLUListElement>([1,2],{
    delayBeforeInsert: 250,
    removingClass: "removed",
    delayBeforeRemove: 400
  });
  const addNumber = () => {
    insertAt(numbers.length, Math.max(...numbers)+1);
  };
  const removeNumber = (index: number) => {
    removeAt(index);
  }
  return (
    <div>
      <h2>Simple Number List</h2>
      <ul ref={parent} className='number-list'>
        {numbers.map((number, index) => (
          <li className='number' data-index={index} key={number}>
            {number}
            <button className='remove-button' onClick={() => removeNumber(index)}>x</button>
          </li>
        ))}
      </ul>
      <button onClick={addNumber}>Add Number</button>
    </div>
  );
};

export default NumberList;
