// docs/src/components/examples/react/SingleVerticalListOfPokemons.tsx
import { useDragAndDrop } from "fluid-dnd/react";
import type { Pokemon } from "../Pokemon";
import { fetchPokemons } from "@/server/pokemonServer";
import { PokemonComponent } from "./PokemonComponent";
import { useEffect, useState } from "react";
import { TouchDelaySilder } from "./TouchDelaySilder.tsx";

export const SingleVerticalListOfPokemons: React.FC = () => {
	const [delay, setDelay] = useState(150);
	const [parent, listOfPokemons, setPokemons] = useDragAndDrop<Pokemon, HTMLDivElement>([], {
		draggingClass: "dragging-pokemon",
		delayBeforeTouchMoveEvent: delay
	});
	function isMobileDevice() {
		return /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent);
	}
	useEffect(() => {
		const fetchPokemonse = async () => {
			const newPokemons = await fetchPokemons(3);
			setPokemons(newPokemons);
		};
		fetchPokemonse();
	}, []);

	return (
		<div className="flex-col gap-4">
			<div className="flex max-sm:justify-center items-start">
				<div
					ref={parent}
					className="bg-gray-200/60 border-solid border-black/40 rounded-2xl w-60 border-4 p-4 block"
				>
					{listOfPokemons.map((pokemon, index) => (
						<PokemonComponent key={pokemon.name} index={index} pokemon={pokemon} />
					))}
				</div>
			</div>
			{	
				isMobileDevice() && 
				<TouchDelaySilder
					value={delay}
					changeDelay={(newDelay) => {
						setDelay(newDelay);
					}}
				/>
			}
		</div>
	);
};

// docs/src/components/examples/svelte/SingleVerticalListOfPokemons.svelte
<script lang="ts">
  import { useDragAndDrop } from "fluid-dnd/svelte";
  import type { Pokemon } from "../Pokemon";
  import PokemonComponent from "./PokemonComponent.svelte";
  import { fetchPokemons } from "@/server/pokemonServer";
  import TouchDelaySilder from "./touchDelaySilder.svelte";

  let delay = $state(150);
  let pokemons = $state([] as Pokemon[]);
  let parent: HTMLElement;
  fetchPokemons(3).then((newPokemons) => {
      pokemons.push(...newPokemons);
  });
  const changeDelay = (newDelay:number) => {
    delay = newDelay;
    if (parent) {
      dragAndDropAction(parent);
    }
  }
  const [ dragAndDropAction ] = $derived(useDragAndDrop(pokemons, {
      draggingClass: "dragging-pokemon",
      delayBeforeTouchMoveEvent: delay
    }));
 function isMobileDevice() {
	return /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent);
}
</script>
	<div class="flex-col gap-4">
    <div class="flex max-sm:justify-center items-start">
      <div
        bind:this={parent}
        use:dragAndDropAction
        class="bg-gray-200/60 border-solid border-black/40 rounded-2xl w-60 border-4 p-4 block"
      >
      {#each pokemons as pokemon, index (pokemon.name)}
        <PokemonComponent
          index={index}
          pokemon={pokemon}
        />
      {/each}
      </div>
    </div>
    {#if isMobileDevice()}
      <TouchDelaySilder {changeDelay} />
    {/if}
</div>

<style>

</style>
